apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
