apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    path: charts/ingress-nginx
    repoURL: https://github.com/dommaciek/argo.git
    targetRevision: HEAD
  destination:
    namespace: nginx
    name: in-cluster
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true