apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps2/
    repoURL: https://github.com/dommaciek/argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
